<a href="https://colab.research.google.com/github/EmpanadasNqn/Probabilidad/blob/master/Trabajo_especial_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trabajo Especial 2024

# Ejercicio

A continuación se simulan datos correspondientes a las variables del dataset de clase.

1. Carga de Datos: reemplace el dataframe ´df´de la notebook de clase por ´new_df´ y corra la notebook completa.
2. Calcula medidas de posición y dispersión para la columna age.
3. Utilice la función value_counts de pandas para calcular la probabilidad en lugar de la frecuencia de todos las respuestas posibles de la columna ´zodiac_sign´.
4. Describa el tipo de cada variable aleatoria y responda

- `gender`: ??
- `age`: ??
- `zodiac_sign`: ??
- `profession`: ??
- `junior_programmer_salary`: ??
- `senior_programmer_salary`: ??:

  a. La variable `age`, ¿es discreta o continua?

  b. ¿Qué valores pueden tomar `junior_programmer_salary` y `senior_programmer_salary`?

  c. Los signos del zodiaco siguen un orden (al igual que los días y los meses del año). ¿Podríamos decir que `zodiac_sign` tiene tipo ordinal?

5. Usando los boxplots describa la distribución del ingreso senior en el rango de edad construido y agrupado por ´gender´ . ¿Son simétricas, sesgada a la izquierda o a la derecha?

A continuación vamos a  simular los datos.

In [ ]:
import io
import pandas
import seaborn

print(seaborn.__version__)
BLUE = '#35A7FF'
RED = '#FF5964'
GREEN = '#6BF178'
YELLOW = '#FFE74C'
# Con esto hacemos los gráficos más grandes, adecuados para las presentaciones.
#seaborn.set_context(context='talk', font_scale=1.2)

0.13.2

### Simulación:
Observar que hay una semilla que permite que sea reproducible, y que las variables son creadas con distribuciones de probabilidad.

In [ ]:
import numpy
numpy.random.seed(0)

N = 100

new_data = {}
new_data['gender'] = numpy.random.choice(
    ['Mujer', 'Hombre', 'Otro', 'Prefiero no decirlo'], size=N,
    p=[0.3, 0.65, 0.01, 0.04])
new_data['age'] = numpy.random.normal(35, 15, size=N).astype(numpy.int32)
new_data['zodiac_sign'] = numpy.random.choice(
    ['Aries', 'Tauro', 'Géminis', 'Cáncer', 'Leo', 'Virgo', 'Libra', 'Escorpio',
     'Sagitario', 'Capricornio', 'Acuario', 'Picis'], size=N)
new_data['profession'] = numpy.random.choice(
    ['Programador', 'Profesor', 'Maestro', 'Contador',
     'Ingeniero', 'Economista', 'Estudiante', 'Matemático',
     'Físico'], size=N)
round_100 = lambda x: int(int(x) / 100) * 1000
new_data['junior_programmer_salary'] = numpy.vectorize(round_100)(
    numpy.random.lognormal(mean=8.5, sigma=0.25, size=N))
new_data['senior_programmer_salary'] = numpy.vectorize(round_100)(
    numpy.random.lognormal(mean=9.5, sigma=0.25, size=N))
new_df = pandas.DataFrame(new_data)
new_df

,gender,age,zodiac_sign,profession,junior_programmer_salary,senior_programmer_salary
0,Hombre,17,Cáncer,Profesor,55000,138000
1,Hombre,48,Escorpio,Ingeniero,50000,131000
2,Hombre,41,Sagitario,Ingeniero,48000,160000
3,Hombre,11,Virgo,Ingeniero,58000,123000
4,Hombre,57,Aries,Programador,62000,243000
...,...,...,...,...,...,...
95,Mujer,45,Leo,Estudiante,57000,115000
96,Hombre,22,Virgo,Economista,56000,137000
97,Mujer,24,Aries,Maestro,45000,128000
98,Hombre,28,Cáncer,Matemático,50000,154000
99,Mujer,35,Acuario,Profesor,45000,121000

In [ ]:
new_df[new_df.gender == 'Hombre'].junior_programmer_salary.describe()

count       61.000000
mean     52786.885246
std      11734.727314
min      27000.000000
25%      44000.000000
50%      50000.000000
75%      62000.000000
max      80000.000000
Name: junior_programmer_salary, dtype: float64

In [ ]:
new_df[new_df.gender == 'Hombre'].senior_programmer_salary.describe()

count        61.000000
mean     144098.360656
std       40193.575323
min       74000.000000
25%      115000.000000
50%      138000.000000
75%      165000.000000
max      269000.000000
Name: senior_programmer_salary, dtype: float64

### Guardemos el dataset simulado

In [ ]:
from google.colab import files
new_df.to_csv('generated_dataset.csv')
files.download('generated_dataset.csv')